## using all data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics 
from sklearn import model_selection
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
data=pd.read_csv('amazon_baby.csv')
data.head()

,name,review,rating
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5

In [3]:
data.shape

(183531, 3)

In [4]:
#prod=data[data['name']=='Vulli Sophie the Giraffe Teether']
prod=data.copy()
prod.head()

,name,review,rating
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5

## count words directly for selected words

In [5]:
sel_words = ['awesome', 'great', 'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful', 'wow', 'hate']
cv=CountVectorizer(vocabulary=sel_words)

In [6]:
prod['review'].fillna('0',inplace=True)

In [7]:
cv_fit=cv.fit_transform(prod['review'])
words=cv.get_feature_names()
counts=cv_fit.toarray()
#cv.vocabulary_

In [8]:
counts.shape

(183531, 11)

In [9]:
#print(words)
len(prod)

183531

In [10]:
counts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
d=[]
for i in range(len(counts)):
    mapped=zip(words,counts[i])
    mapped=dict(mapped)
    d.append(mapped)
len(d)

183531

In [12]:
prod['spec_count']=d
prod.head()

,name,review,rating,spec_count
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am..."
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am..."
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am..."
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am..."
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am..."

In [13]:
def awesome(d):
    if 'awesome' in d:
        return d['awesome']
    else:
        return 0

In [14]:
#prod['awesome']=prod['spec_count'].apply(awesome)
#prod.head()

## seperate word count into columns

In [15]:
def cols(d,word):
    if word in d:
        return d[word]
    else:
        return 0

In [16]:
for word in sel_words:
    prod[word]=prod['spec_count'].apply(lambda d: cols(d,word))
prod.columns

Index(['name', 'review', 'rating', 'spec_count', 'awesome', 'great',
       'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful',
       'wow', 'hate'],
      dtype='object')

In [17]:
for word in sel_words:
    prod[word]=prod['spec_count'].apply(lambda d: d.get(word,0))
prod.columns

Index(['name', 'review', 'rating', 'spec_count', 'awesome', 'great',
       'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful',
       'wow', 'hate'],
      dtype='object')

In [18]:
prod.head()

,name,review,rating,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,0,0,0,0,0,0,0
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,1,0,0,0,0,0,0
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,0,0,0,0,0,0,0
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,2,0,0,0,0,0,0
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am...",0,1,0,0,1,0,0,0,0,0,0

## max and min times of word

In [19]:
d={}
for word in sel_words:
    l=prod[word].sum()
    d[word]=l
d

{'awesome': 4075,
 'great': 59536,
 'fantastic': 1765,
 'amazing': 2726,
 'love': 43867,
 'horrible': 1245,
 'bad': 4950,
 'terrible': 1282,
 'awful': 753,
 'wow': 461,
 'hate': 1285}

In [20]:
keys=list(d.keys())
vals=list(d.values())

In [21]:
val=max(vals)
ind=vals.index(val)
print(keys[ind])

great

In [22]:
val=min(vals)
ind=vals.index(val)
print(keys[ind])

wow

## give sentiment

In [23]:
prod=prod[prod['rating']!=3]
prod.head()

,name,review,rating,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,1,0,0,0,0,0,0
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,0,0,0,0,0,0,0
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,2,0,0,0,0,0,0
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am...",0,1,0,0,1,0,0,0,0,0,0
5,Stop Pacifier Sucking without tears with Thumb...,"When the Binky Fairy came to our house, we did...",5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am...",0,1,0,0,0,0,0,0,0,0,0

In [24]:
prod['sentiment']=(prod['rating']>=4).astype(int)
prod.head()

,name,review,rating,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sentiment
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,1,0,0,0,0,0,0,1
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,0,0,0,0,0,0,0,1
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,"{'awesome': 0, 'great': 0, 'fantastic': 0, 'am...",0,0,0,0,2,0,0,0,0,0,0,1
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am...",0,1,0,0,1,0,0,0,0,0,0,1
5,Stop Pacifier Sucking without tears with Thumb...,"When the Binky Fairy came to our house, we did...",5,"{'awesome': 0, 'great': 1, 'fantastic': 0, 'am...",0,1,0,0,0,0,0,0,0,0,0,1

In [25]:
X=prod.loc[:,sel_words]
Y=prod.loc[:,['sentiment']]
#X=X.values.reshape(-1,1)
Y=Y.values.reshape(-1,)
Y.shape

(166752,)

In [26]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(X,Y,test_size=0.2,random_state=0)

## logistic classifier

In [27]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression(random_state=0)
reg.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
pred_res=reg.predict(x_test)

In [29]:
df=x_test.copy()
df['sent']=y_test
df['pred_sent']=pred_res
df.head()

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent
103733,0,0,0,0,0,0,0,0,0,0,0,1,1
157975,0,0,0,0,0,0,0,0,0,0,0,1,1
127693,0,0,0,0,0,0,0,0,0,0,0,1,1
113718,0,0,0,0,0,0,0,0,0,0,0,0,1
20416,0,0,0,0,1,0,0,0,0,0,0,1,1

In [30]:
prob=reg.predict_proba(x_test)
df['pred_prob']=prob[:,1]
df

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent,pred_prob
103733,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
157975,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
127693,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
113718,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
20416,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
62236,0,1,0,0,0,0,0,0,0,0,0,0,1,0.900647
93741,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
182819,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
108942,0,2,0,0,2,0,0,0,0,0,0,1,1,0.997077
63171,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
27972,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
123316,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
60874,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
89381,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
146248,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
167897,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
129689,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
54150,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
8352,0,1,0,0,0,0,0,0,0,1,0,1,1,0.891590
55700,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
83479,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
93618,0,2,0,0,0,0,0,0,0,0,0,1,1,0.955655
130762,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
73991,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
174021,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
17830,1,0,0,0,0,0,0,0,0,0,0,1,1,0.924866
62700,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
33106,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
156734,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
67422,0,1,1,0,1,0,0,0,0,0,0,1,1,0.988857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33630,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
83222,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
92096,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
166152,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
43836,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
36456,0,1,0,0,0,1,0,0,0,0,0,1,0,0.483844
152136,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
127926,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
44693,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
26178,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
138229,0,1,0,0,0,0,0,0,0,0,0,0,1,0.900647
111411,0,2,0,0,0,0,0,0,0,0,0,1,1,0.955655
19693,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
167580,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
111121,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
45882,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
3544,0,0,0,0,3,1,0,0,0,0,0,1,1,0.961290
27916,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
98679,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
104745,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
57207,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
55971,1,0,0,0,0,0,0,0,0,0,0,1,1,0.924866
79937,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
175023,0,0,0,0,1,0,0,0,0,0,0,1,1,0.938162
52638,0,4,0,0,0,0,0,0,0,0,0,1,1,0.991856
62773,0,1,0,0,0,0,0,0,0,0,0,1,1,0.900647
183290,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238
608,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
89302,0,0,0,0,0,0,0,0,0,0,0,0,1,0.792238
162123,0,0,0,0,0,0,0,0,0,0,0,1,1,0.792238

In [31]:
#score=reg.score(y_test,pred_res)
print(y_test)
print(pred_res)
print(x_test)

[1 1 1 ... 0 0 1]
[1 1 1 ... 1 1 1]
        awesome  great  fantastic  amazing  love  horrible  bad  terrible  \
103733        0      0          0        0     0         0    0         0
157975        0      0          0        0     0         0    0         0
127693        0      0          0        0     0         0    0         0
113718        0      0          0        0     0         0    0         0
20416         0      0          0        0     1         0    0         0
62236         0      1          0        0     0         0    0         0
93741         0      0          0        0     0         0    0         0
182819        0      0          0        0     0         0    0         0
108942        0      2          0        0     2         0    0         0
63171         0      0          0        0     0         0    0         0
27972         0      0          0        0     1         0    0         0
123316        0      0          0        0     0         0    0         0
60874         0      0          0        0     1         0    0         0
89381         0      1          0        0     0         0    0         0
146248        0      1          0        0     0         0    0         0
167897        0      1          0        0     0         0    0         0
129689        0      0          0        0     0         0    0         0
54150         0      0          0        0     0         0    0         0
8352          0      1          0        0     0         0    0         0
55700         0      0          0        0     0         0    0         0
83479         0      0          0        0     0         0    0         0
93618         0      2          0        0     0         0    0         0
130762        0      0          0        0     0         0    0         0
73991         0      0          0        0     0         0    0         0
174021        0      1          0        0     0         0    0         0
17830         1      0          0        0     0         0    0         0
62700         0      0          0        0     0         0    0         0
33106         0      0          0        0     0         0    0         0
156734        0      0          0        0     0         0    0         0
67422         0      1          1        0     1         0    0         0
...         ...    ...        ...      ...   ...       ...  ...       ...
33630         0      0          0        0     0         0    0         0
83222         0      0          0        0     0         0    0         0
92096         0      0          0        0     0         0    0         0
166152        0      0          0        0     0         0    0         0
43836         0      0          0        0     1         0    0         0
36456         0      1          0        0     0         1    0         0
152136        0      0          0        0     1         0    0         0
127926        0      0          0        0     0         0    0         0
44693         0      0          0        0     1         0    0         0
26178         0      0          0        0     0         0    0         0
138229        0      1          0        0     0         0    0         0
111411        0      2          0        0     0         0    0         0
19693         0      0          0        0     0         0    0         0
167580        0      0          0        0     0         0    0         0
111121        0      0          0        0     0         0    0         0
45882         0      0          0        0     0         0    0         0
3544          0      0          0        0     3         1    0         0
27916         0      0          0        0     1         0    0         0
98679         0      1          0        0     0         0    0         0
104745        0      0          0        0     0         0    0         0
57207         0      0          0        0     0         0    0         0
55971         1      0          0        0     0         0    0         0
79937         0      0          0        0     1         0    0         0
175023        0      0          0        0     1         0    0         0
52638         0      4          0        0     0         0    0         0
62773         0      1          0        0     0         0    0         0
183290        0      0          0        0     0         0    0         0
608           0      0          0        0     0         0    0         0
89302         0      0          0        0     0         0    0         0
162123        0      0          0        0     0         0    0         0

        awful  wow  hate
103733      0    0     0
157975      0    0     0
127693      0    0     0
113718      0    0     0
20416       0    0     0
62236       0    0     0
93741       0    0     0
182819      0    0     0
108942      0    0     0
63171       0    0     0
27972       0    0     0
123316      0    0     0
60874       0    0     0
89381       0    0     0
146248      0    0     0
167897      0    0     0
129689      0    0     0
54150       0    0     0
8352        0    1     0
55700       0    0     0
83479       0    0     0
93618       0    0     0
130762      0    0     0
73991       0    0     0
174021      0    0     0
17830       0    0     0
62700       0    0     0
33106       0    0     0
156734      0    0     0
67422       0    0     0
...       ...  ...   ...
33630       0    0     0
83222       0    0     0
92096       0    0     0
166152      0    0     0
43836       0    0     0
36456       0    0     0
152136      0    0     0
127926      0    0     0
44693       0    0     0
26178       0    0     0
138229      0    0     0
111411      0    0     0
19693       0    0     0
167580      0    0     0
111121      0    0     0
45882       0    0     0
3544        0    0     0
27916       0    0     0
98679       0    0     0
104745      0    0     0
57207       0    0     0
55971       0    0     0
79937       0    0     0
175023      0    0     0
52638       0    0     0
62773       0    0     0
183290      0    0     0
608         0    0     0
89302       0    0     0
162123      0    0     0

[33351 rows x 11 columns]

In [32]:
score1=reg.score(x_test,y_test)
score1

0.8458217144913196

In [33]:
coeff=reg.coef_
print(coeff.shape)
coeff=coeff.reshape(11)
print(coeff.shape)

(1, 11)
(11,)

In [34]:
coeff=coeff.tolist()
coeff

[1.1719033863215012,
 0.8659635741317872,
 0.9003921294588427,
 1.0541811283264924,
 1.3809296735608239,
 -2.2690806001663058,
 -0.9752497120247416,
 -2.209990996060695,
 -2.0557965775408253,
 -0.09734750131006584,
 -1.4335181343223773]

In [35]:
z=zip(sel_words,coeff)
z=dict(z)
z

{'awesome': 1.1719033863215012,
 'great': 0.8659635741317872,
 'fantastic': 0.9003921294588427,
 'amazing': 1.0541811283264924,
 'love': 1.3809296735608239,
 'horrible': -2.2690806001663058,
 'bad': -0.9752497120247416,
 'terrible': -2.209990996060695,
 'awful': -2.0557965775408253,
 'wow': -0.09734750131006584,
 'hate': -1.4335181343223773}

In [36]:
z_sorted=sorted(z.items(),  key=lambda kv  :  (kv[1],kv[0])  )
z_sorted

[('horrible', -2.2690806001663058),
 ('terrible', -2.209990996060695),
 ('awful', -2.0557965775408253),
 ('hate', -1.4335181343223773),
 ('bad', -0.9752497120247416),
 ('wow', -0.09734750131006584),
 ('great', 0.8659635741317872),
 ('fantastic', 0.9003921294588427),
 ('amazing', 1.0541811283264924),
 ('awesome', 1.1719033863215012),
 ('love', 1.3809296735608239)]

In [37]:
keys=list(z.keys())
vals=list(z.values())
val=max(vals)
ind=vals.index(val)
print(keys[ind])

love

In [38]:
val=min(vals)
ind=vals.index(val)
print(keys[ind])

horrible

In [39]:
y_train.sum()

112270

In [40]:
y_train.shape

(133401,)

In [41]:
y_test.sum()

27989

In [42]:
y_test.shape

(33351,)

In [43]:
acc=27989/33351
acc

0.8392252106383616