## for baby diaper

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics 
from sklearn import model_selection
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
data=pd.read_csv('amazon_baby.csv')
data.head()

,name,review,rating
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5

In [3]:
data.shape

(183531, 3)

In [4]:
df=pd.DataFrame(data.groupby(['name']).size())
df=df.sort_values(by=[0],ascending=False)
df.head()

                                                      0
name
Vulli Sophie the Giraffe Teether                    785
Simple Wishes Hands-Free Breastpump Bra, Pink, ...  562
Infant Optics DXR-5 2.4 GHz Digital Video Baby ...  561
Baby Einstein Take Along Tunes                      547
Cloud b Twilight Constellation Night Light, Turtle  520

In [5]:
prod=data[data['name']=='Baby Trend Diaper Champ']
#prod=data
prod.head()

,name,review,rating
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4
313,Baby Trend Diaper Champ,This is a good product to start and very easy ...,3
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5

## word count

In [6]:
cv=CountVectorizer()

In [7]:
prod['review'].fillna('0',inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [8]:
cv_fit=cv.fit_transform(prod['review'])
words=cv.get_feature_names()
counts=cv_fit.toarray()
#cv.vocabulary_

In [9]:
counts.shape

(333, 2686)

In [10]:
#print(words)
len(prod)

333

In [11]:
counts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
d=[]
for i in range(len(counts)):
    mapped=zip(words,counts[i])
    mapped=dict(mapped)
    d.append(mapped)
len(d)

333

In [13]:
prod['count']=d
prod.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,name,review,rating,count
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,..."
313,Baby Trend Diaper Champ,This is a good product to start and very easy ...,3,"{'00': 0, '05': 0, '10': 1, '100': 0, '11': 0,..."
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,..."
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,..."
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,..."

## specific count

In [14]:
sel_words = ['awesome', 'great', 'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful', 'wow', 'hate']
def filters(d):
    d_new={}
    for c in d:
        if c in sel_words:
            d_new[c]=d[c]
    return d_new

In [15]:
prod['spec_count']=prod['count'].apply(filters)
prod.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,name,review,rating,count,spec_count
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'..."
313,Baby Trend Diaper Champ,This is a good product to start and very easy ...,3,"{'00': 0, '05': 0, '10': 1, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'..."
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'..."
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'..."
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'..."

In [16]:
def awesome(d):
    if 'awesome' in d:
        return d['awesome']
    else:
        return 0

In [17]:
#prod['awesome']=prod['spec_count'].apply(awesome)
#prod.head()

In [18]:
def cols(d,word):
    if word in d:
        return d[word]
    else:
        return 0

In [19]:
for word in sel_words:
    prod[word]=prod['spec_count'].apply(lambda d: cols(d,word))
prod.columns

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Index(['name', 'review', 'rating', 'count', 'spec_count', 'awesome', 'great',
       'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful',
       'wow', 'hate'],
      dtype='object')

In [20]:
for word in sel_words:
    prod[word]=prod['spec_count'].apply(lambda d: d.get(word,0))
prod.columns

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Index(['name', 'review', 'rating', 'count', 'spec_count', 'awesome', 'great',
       'fantastic', 'amazing', 'love', 'horrible', 'bad', 'terrible', 'awful',
       'wow', 'hate'],
      dtype='object')

In [21]:
prod.head()

,name,review,rating,count,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
313,Baby Trend Diaper Champ,This is a good product to start and very easy ...,3,"{'00': 0, '05': 0, '10': 1, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,1,0,0,0,0
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,1,0,0,0,0,0,0

## max and min times of words

In [23]:
d={}
for word in sel_words:
    l=prod[word].sum()
    d[word]=l
d

{'awesome': 3,
 'great': 103,
 'fantastic': 3,
 'amazing': 2,
 'love': 99,
 'horrible': 6,
 'bad': 39,
 'terrible': 1,
 'awful': 1,
 'wow': 2,
 'hate': 2}

In [24]:
keys=list(d.keys())
vals=list(d.values())

In [25]:
val=max(vals)
ind=vals.index(val)
print(keys[ind])

great

In [26]:
val=min(vals)
ind=vals.index(val)
print(keys[ind])

terrible

## give sentiment

In [27]:
prod=prod[prod['rating']!=3]
prod.head()

,name,review,rating,count,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,1,0,0,0,0,0,0
317,Baby Trend Diaper Champ,Two girlfriends and two family members put me ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 1, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,1,0,1,0,0,0,1,0

In [28]:
prod['sentiment']=(prod['rating']>=4).astype(int)
prod.head()

,name,review,rating,count,spec_count,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sentiment
312,Baby Trend Diaper Champ,Ok - newsflash. Diapers are just smelly. We'...,4,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0,1
314,Baby Trend Diaper Champ,"My husband and I selected the Diaper ""Champ"" m...",1,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0,0
315,Baby Trend Diaper Champ,Excellent diaper disposal unit. I used it in ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,0,0,0,0,0,0,0,1
316,Baby Trend Diaper Champ,We love our diaper champ. It is very easy to ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 0, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,0,1,0,0,0,0,0,0,1
317,Baby Trend Diaper Champ,Two girlfriends and two family members put me ...,5,"{'00': 0, '05': 0, '10': 0, '100': 0, '11': 0,...","{'amazing': 1, 'awesome': 0, 'awful': 0, 'bad'...",0,0,0,1,0,1,0,0,0,1,0,1

In [29]:
X=prod.loc[:,sel_words]
Y=prod.loc[:,['sentiment']]
#X=X.values.reshape(-1,1)
Y=Y.values.reshape(-1,)
Y.shape

(298,)

In [30]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(X,Y,test_size=0.2,random_state=0)

## logistic regression

In [31]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression(random_state=0)
reg.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [32]:
pred_res=reg.predict(x_test)

In [33]:
df=x_test.copy()
df['sent']=y_test
df['pred_sent']=pred_res
df.head()

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent
435,0,0,0,0,1,0,0,0,0,0,0,1,1
505,0,0,0,0,0,0,1,0,0,0,0,1,1
325,0,0,0,0,0,0,0,0,0,0,0,1,1
557,0,1,0,0,0,0,0,0,0,0,0,1,1
541,0,1,0,0,0,0,0,0,0,0,0,0,1

In [34]:
prob=reg.predict_proba(x_test)
df['pred_prob']=prob[:,1]
df

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent,pred_prob
435,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
505,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
325,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
557,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
541,0,1,0,0,0,0,0,0,0,0,0,0,1,0.863750
392,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
546,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
503,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
522,0,0,0,0,0,0,0,1,0,0,0,0,1,0.768914
553,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
391,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
330,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
602,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
429,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
337,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
566,0,0,0,0,0,0,1,0,0,0,0,0,1,0.683793
596,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
460,1,0,0,0,0,0,0,0,0,0,0,1,1,0.686680
575,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
636,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
382,0,1,0,0,1,0,0,0,0,0,0,1,1,0.972340
479,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
581,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
537,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
412,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
369,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
446,0,0,0,0,3,0,0,0,0,0,0,1,1,0.998241
591,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
626,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
381,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
321,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
472,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
549,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
523,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
560,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
513,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
318,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
578,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
562,0,1,0,0,0,0,0,0,0,0,1,1,1,0.877478
521,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
350,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
564,0,2,0,0,0,0,0,0,0,0,0,1,1,0.923536
510,0,1,0,0,0,0,0,0,0,0,0,0,1,0.863750
630,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
320,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
362,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
426,0,2,0,0,1,0,0,0,0,0,0,1,1,0.985289
574,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
501,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
424,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
372,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
628,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
496,0,0,0,0,0,0,0,0,0,0,0,0,1,0.768914
341,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
384,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
644,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
570,0,0,0,0,0,0,1,0,0,0,0,0,1,0.683793
459,0,0,0,0,3,0,0,0,0,0,0,1,1,0.998241
377,0,1,0,0,1,0,0,0,0,0,0,1,1,0.972340
638,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914

In [35]:
#score=reg.score(y_test,pred_res)
print(y_test)
print(pred_res)
print(x_test)

[1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
     awesome  great  fantastic  amazing  love  horrible  bad  terrible  awful  \
435        0      0          0        0     1         0    0         0      0
505        0      0          0        0     0         0    1         0      0
325        0      0          0        0     0         0    0         0      0
557        0      1          0        0     0         0    0         0      0
541        0      1          0        0     0         0    0         0      0
392        0      1          0        0     0         0    0         0      0
546        0      0          0        0     1         0    0         0      0
503        0      0          0        0     0         0    0         0      0
522        0      0          0        0     0         0    0         1      0
553        0      0          0        0     0         0    0         0      0
391        0      0          0        0     0         0    0         0      0
330        0      0          0        0     0         0    0         0      0
602        0      0          0        0     0         0    0         0      0
429        0      1          0        0     0         0    0         0      0
337        0      0          0        0     0         0    0         0      0
566        0      0          0        0     0         0    1         0      0
596        0      0          0        0     1         0    0         0      0
460        1      0          0        0     0         0    0         0      0
575        0      1          0        0     0         0    0         0      0
636        0      0          0        0     0         0    0         0      0
382        0      1          0        0     1         0    0         0      0
479        0      0          0        0     0         0    0         0      0
581        0      0          0        0     1         0    0         0      0
537        0      0          0        0     0         0    0         0      0
412        0      0          0        0     1         0    0         0      0
369        0      0          0        0     0         0    0         0      0
446        0      0          0        0     3         0    0         0      0
591        0      1          0        0     0         0    0         0      0
626        0      0          0        0     0         0    0         0      0
381        0      0          0        0     0         0    0         0      0
321        0      0          0        0     0         0    0         0      0
472        0      0          0        0     0         0    0         0      0
549        0      0          0        0     0         0    0         0      0
523        0      0          0        0     0         0    1         0      0
560        0      0          0        0     0         0    0         0      0
513        0      0          0        0     1         0    0         0      0
318        0      0          0        0     0         0    1         0      0
578        0      0          0        0     0         0    0         0      0
562        0      1          0        0     0         0    0         0      0
521        0      0          0        0     1         0    0         0      0
350        0      0          0        0     0         0    0         0      0
564        0      2          0        0     0         0    0         0      0
510        0      1          0        0     0         0    0         0      0
630        0      0          0        0     1         0    0         0      0
320        0      0          0        0     0         0    0         0      0
362        0      0          0        0     0         0    0         0      0
426        0      2          0        0     1         0    0         0      0
574        0      0          0        0     0         0    0         0      0
501        0      0          0        0     0         0    1         0      0
424        0      0          0        0     0         0    1         0      0
372        0      0          0        0     0         0    0         0      0
628        0      0          0        0     1         0    0         0      0
496        0      0          0        0     0         0    0         0      0
341        0      1          0        0     0         0    0         0      0
384        0      0          0        0     0         0    0         0      0
644        0      0          0        0     0         0    0         0      0
570        0      0          0        0     0         0    1         0      0
459        0      0          0        0     3         0    0         0      0
377        0      1          0        0     1         0    0         0      0
638        0      0          0        0     0         0    0         0      0

     wow  hate
435    0     0
505    0     0
325    0     0
557    0     0
541    0     0
392    0     0
546    0     0
503    0     0
522    0     0
553    0     0
391    0     0
330    0     0
602    0     0
429    0     0
337    0     0
566    0     0
596    0     0
460    0     0
575    0     0
636    0     0
382    0     0
479    0     0
581    0     0
537    0     0
412    0     0
369    0     0
446    0     0
591    0     0
626    0     0
381    0     0
321    0     0
472    0     0
549    0     0
523    0     0
560    0     0
513    0     0
318    0     0
578    0     0
562    0     1
521    0     0
350    0     0
564    0     0
510    0     0
630    0     0
320    0     0
362    0     0
426    0     0
574    0     0
501    0     0
424    0     0
372    0     0
628    0     0
496    0     0
341    0     0
384    0     0
644    0     0
570    0     0
459    0     0
377    0     0
638    0     0

In [36]:
score1=reg.score(x_test,y_test)
score1

0.8166666666666667

In [37]:
coeff=reg.coef_
print(coeff.shape)
coeff=coeff.reshape(11)
print(coeff.shape)

(1, 11)
(11,)

In [38]:
coeff=coeff.tolist()
coeff

[-0.417548035958652,
 0.6446022751788382,
 0.3056789849934201,
 0.4190235653500622,
 1.7129283579523373,
 -0.9609309509479517,
 -0.4309337593820634,
 0.0,
 0.026893536510078943,
 0.4190235653500622,
 0.12196888651974021]

In [39]:
z=zip(sel_words,coeff)
z=dict(z)
z

{'awesome': -0.417548035958652,
 'great': 0.6446022751788382,
 'fantastic': 0.3056789849934201,
 'amazing': 0.4190235653500622,
 'love': 1.7129283579523373,
 'horrible': -0.9609309509479517,
 'bad': -0.4309337593820634,
 'terrible': 0.0,
 'awful': 0.026893536510078943,
 'wow': 0.4190235653500622,
 'hate': 0.12196888651974021}

In [40]:
z_sorted=sorted(z.items(),  key=lambda kv  :  (kv[1],kv[0])  )
z_sorted

[('horrible', -0.9609309509479517),
 ('bad', -0.4309337593820634),
 ('awesome', -0.417548035958652),
 ('terrible', 0.0),
 ('awful', 0.026893536510078943),
 ('hate', 0.12196888651974021),
 ('fantastic', 0.3056789849934201),
 ('amazing', 0.4190235653500622),
 ('wow', 0.4190235653500622),
 ('great', 0.6446022751788382),
 ('love', 1.7129283579523373)]

In [41]:
keys=list(z.keys())
vals=list(z.values())
val=max(vals)
ind=vals.index(val)
print(keys[ind])

love

In [42]:
val=min(vals)
ind=vals.index(val)
print(keys[ind])

horrible

In [43]:
df.head()

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent,pred_prob
435,0,0,0,0,1,0,0,0,0,0,0,1,1,0.948589
505,0,0,0,0,0,0,1,0,0,0,0,1,1,0.683793
325,0,0,0,0,0,0,0,0,0,0,0,1,1,0.768914
557,0,1,0,0,0,0,0,0,0,0,0,1,1,0.863750
541,0,1,0,0,0,0,0,0,0,0,0,0,1,0.863750

In [44]:
df=df.sort_values(by="pred_prob",ascending=False)
df.head()

,awesome,great,fantastic,amazing,love,horrible,bad,terrible,awful,wow,hate,sent,pred_sent,pred_prob
446,0,0,0,0,3,0,0,0,0,0,0,1,1,0.998241
459,0,0,0,0,3,0,0,0,0,0,0,1,1,0.998241
426,0,2,0,0,1,0,0,0,0,0,0,1,1,0.985289
377,0,1,0,0,1,0,0,0,0,0,0,1,1,0.972340
382,0,1,0,0,1,0,0,0,0,0,0,1,1,0.972340

In [45]:
data.loc[446,'review']

"I received my Diaper Champ at my baby shower for the birth of my first son 11 months ago. I use it faithfully every day and love the ease and convenience of only having to change the bag once a week! I love that you can use regular kitchen-size trash bags and don't need to purchase any special expensive bags. One thing you might want to be careful of, however...make sure you do not throw loose baby wipes into the Diaper Champ or else the flip mechanism can become jammed and after time will not seal properly due to having to pull out wipes that are stuck. I love my diaper champ so much, I have asked for a second one for my upcoming baby shower for my second son."